### PR TITLE
Fixing a minor array indexing bug with greyscale textures.

### PR DESCRIPTION
**Pull request by authenticate**
Hi,

This is a minor update to fix an indexing issue.  The following line was out of bounds with the array:

```C++
uint8_t *end_position = &_pixels[_width * _height * format_bytes];
```

"(_width * _height * format_bytes)" is equal to the entire size of the array.  This will be one index too big.

I also updated the looping structure.  I think the 'while' loop is clearer to the reader in this particular case since we are looping in groups of pixels instead of each index sequentially.

Let me know if there are any issues.

Thanks.

### CODE REVIEW

**Comment by Bertram25** [comment]
Will be on this one tonight. :)

**Comment by Bertram25** [comment]
For you to know, I'm preparing a patch to expose the *GrayScale() functionalities to the script level in a better way. I'll use that to make your change testable, and merge afterward.

**Comment by Bertram25** [comment]
I've tested and your patch is actually breaking grayscale support:
screenshot_2
To try it, rebase on master, compile with debug features and use the debug_map_sprites script. A the end of it, the sprite should become grayscaled.

**Comment by authenticate** [comment]
Sorry about that.

I was storing the sum as an eight bit integer instead of a larger integer to hold the entire, scaled value.

In addition, I made a small change to the "ListDirectory" function for Windows.  It was not actually returning any files which caused the "Debug Scripts" menu option to never have any debug scripts.  I probably should have noticed that sooner.

Finally, I changed "data/debug" to "./data/debug".  If this causes any problems on Linux or OS X, let me know and I'll revert it and change something else to make things work.  This just happened to be the simplest solution to get things moving at the time.

Thanks.

**Comment by Bertram25** [comment]
Ok, I'll test asap. I'm not sure the change about data/ will be fine, though. But let me test first. :)

**Pull request merged**
