### PR TITLE
Add/GitHub actions

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your project. I add github-actions. I hope it is useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by theavege** [comment]
@akien-mga Could you accept the PR?

**Comment by akien-mga** [comment]
I'm not a maintainer of this project, just a contributor from a decade ago :)
I don't have merge rights, but also no time to be involved anymore.

And the project hasn't been actively developed for years so I personally don't see much value in adding a GitHub Actions pipeline that runs weekly if there's no work done on the project. It will just create work if/when the pipeline inevitably breaks because GitHub changes their `ubuntu-latest` runner (which will happen in a few days actually).

If a GitHub Actions pipeline was added, my recommendation would be to do it properly with the setup for dependencies and build commands all in the yml as different steps, instead of offloading that to a bash file. The existing Travis CI and AppVeyor config can be taken for reference. But again, this repo isn't actively developed so I wouldn't count on any PR being merged.

**Comment by theavege** [comment]
@akien-mga Thank you for your answer.
@Bertram25  Could you accept the PR?

**Comment by Bertram25** [comment]
Hey,

@theavege I'll have to be that rude guy, but please don't take this badly.

@akien-mga might not be a maintainer while he definitely helps in that regards a long time ago. He's definitely on point.

I'm not planning to maintain actively github actions that don't make sense for this project, while I hope you had a bit of fun with the game anyway. That's why it's here for.
And even though, I wouldn't want to merge this in this state.

It feels like you're prepping to do your own stuff on your side and wish you well on that part. As for me, would I continue this project, I would continue it on Godot (@akien-mga pun intended ;])

I'll close this PR shortly but thanks for your interest.
Cheers,

**Comment by theavege** [comment]
@Bertram25 No problem. I like ValyriaTear. I will wait ValyriaTear on Godot. But You should be careful, [unknown-horizons](http://www.unknown-horizons.org/) couldn't migrate to Godot.

**Comment by Bertram25** [comment]
Looks like they just moved to 4.3 one month ago: https://github.com/unknown-horizons/godot-port/commit/8f765b90397e882c76dd0b723e1a0f4aada66f8a

Just to clarify, I'm actually working on several Godot projects but Valyria Tear is not in the pile, at least not yet. I wouldn't have your hopes too high.
That said, that would a fun candidate, but with a lot of necessary commitment.

**Pull request closed without merging**
