### PR TITLE
Set up AppVeyor builds

### PR DESCRIPTION
**Pull request by gunchleoc**
- Set up AppVeyor Windows builds
- Fix Start Menu shortcuts in NSIS installer

There was a lot of experimentation involved, so I recommend that you squash the commits when merging.

All you need to do to trigger builds is to register and link a project on appveyor.com. You might also want to add badges or webhooks to GitHub - I have not tested that part.

Latest build on my test project: https://ci.appveyor.com/project/GunChleoc/valyriatear/builds/19844096

### CODE REVIEW

**Comment by Bertram25** [comment]
Before you run away in total dismay, I'm having a look at this atm ;)

**Comment by Bertram25** [comment]
Looks good AFAICS. Safe enough to squash, rebase and merge. :)

**Comment by Bertram25** [comment]
Was done. We now have AppVeyor builds and artifacts thanks to you! :D 

I'll advertise this on the blog asap. Always good to have some news.

**Comment by gunchleoc** [comment]
Excellent! :)

Do you want Travis as well? We could do Linux builds with various compiler versions and Mac builds, but no binaries. Which are the earliest Clang/GXX versions we are supporting?

**Comment by Bertram25** [comment]
@gunchleoc Hey! I took the time to properly setup everyhing for Windows here. This way, I can easily try things out. (Sry, took my time).
As for Travis, I thought I had this already, as can witness the .travis.yml file in the source code and here:
https://travis-ci.org/ValyriaTear/ValyriaTear

**Comment by gunchleoc** [comment]
I wasn't aware that Travis is already running - maybe I just forgot

**Pull request closed without merging**
