### PR TITLE
 Change local localedir to data/locale

### PR DESCRIPTION
**Pull request by gunchleoc**
- Binary translations are now residing in 'data/locale'
- Generate translation binaries directly into 'data/locale'
- Remove now obsolete locale file copying from the NSIS installer
- Replace the 'LINGUAS' file by directory iteration
- Mac XCode project still needs fixing

### CODE REVIEW

**Comment by gunchleoc** [comment]
This is some preliminary work for https://github.com/ValyriaTear/ValyriaTear/issues/341

**Comment by Bertram25** [comment]
Re,

This PR has several flaws AFAICS, but feel free to tell if I'm wrong:
- I don't want directory iteration since I want to be able to exclude very incomplete languages. Plus, the LINGUAS file is very common when using Gettext.
- It seems you removed the mo file from the nsis installer script without adding the equivalent.
- You changed po/ to locale/. Why not. But it seems the c++ codepart wasn't adapted. Did you test it?

**Comment by gunchleoc** [comment]
* Not including locales could be done via the configuration Lua file during the release process? The reason that I removed the LINGUAS is that we're defining our language list twice, once in the LINGUAS and once in the configuration Lua. I could add the LINGUAS back in though if you prefer, because you'll be the one doing the release work. So, you decide :)
* Removing the mo files in the NSIS installer should be fine, because they are now sitting under the data directory, which is already being included in full. I have not tested this though.
* Calling the directory "locale" is pretty standard from what I've seen on other projects. It will also make things easier when we move to multiple text domains for Episode II, because it will save us from having to implement a filtering algorithm for the PO directory. And the C++ changes are there: https://github.com/ValyriaTear/ValyriaTear/pull/620/files#diff-3c7277f6b0eeafc04ea12ef16a99b34a

I tested everything on Linux, so no tests for NSIS or Mac.

**Comment by Bertram25** [comment]
> Not including locales could be done via the configuration Lua file during the release process? The reason that I removed the LINGUAS is that we're defining our language list twice, once in the LINGUAS and once in the configuration Lua. I could add the LINGUAS back in though if you prefer, because you'll be the one doing the release work. So, you decide :)

Ah, now you tell it, it is actually true and a good point. I stand corrected. Let's remove the LINGUAS file. :)

> Removing the mo files in the NSIS installer should be fine, because they are now sitting under the data directory, which is already being included in full. I have not tested this though.

True. I should sleep more, eh eh.

> Calling the directory "locale" is pretty standard from what I've seen on other projects. It will also make things easier when we move to multiple text domains for Episode II, because it will save us from having to implement a filtering algorithm for the PO directory. And the C++ changes are there: https://github.com/ValyriaTear/ValyriaTear/pull/620/files#diff-3c7277f6b0eeafc04ea12ef16a99b34a

As for the locale/ name I had nothing against it at all, I actually skipped the system.cpp file changes completely when reviewing explaining my comment. Again, lack of sleep. In fact, I see nothing wrong with this PR.

So, in the end, my apologies for the really bad review due to lack of sleep.

**Comment by Bertram25** [comment]
I fixed the conflicts and merged. Thanks a lot for all the work done so far :)

**Comment by Bertram25** [comment]
@gunchleoc For information, the next 2 weeks I'll only have access to my phone and won't be able to do more than (hopefully not too bad) reviews ;)
But feel free to discuss any useful subjects or code changes. I'll be able to review, test and code more frequently afterwards.

Cheers,

**Comment by gunchleoc** [comment]
Hi @Bertram25 

Don't worry about the speed of reviews. I hit you with a whole bunch of them out of the blue. This is a hobby, and reviews will take as long as they take ;)

So, don't stress yourself out trying to review anything via phone and enjoy a bit of AFK instead! The PRs will still be there when you get back.

**Comment by Bertram25** [comment]
@gunchleoc  Thanks :) AFK time was indeed a savior thing :) I'm back now and taking the Valyria plane again. :small_airplane:

**Pull request closed without merging**
