### PR TITLE
Added config for Transifex client

### PR DESCRIPTION
**Pull request by gunchleoc**
Added config file for the Transifex client.

Documentation: https://docs.transifex.com/client/introduction

You will need to create a `.transifexrc` in your home directory, then
you can use `tx push -s` to update the reference catalog on Transifex, and `tx pull
-a` to get the latest translations.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good to me, though to avoid cluttering the root dir I'd suggest to put the `.tx` folder in `po/.tx`. That's mostly a matter of taste though, @Bertram25 might think otherwise (and his opinion is what counts ;)).

**Comment by gunchleoc** [comment]
Everybody project that I have seen so far has this in their root directory.

**Comment by Bertram25** [comment]
Let's use the default behavior, even if I agree, it's never great to clutter the root folder.

**Comment by Bertram25** [comment]
Thanks for the addition!

**Comment by gunchleoc** [comment]
Thanks for being a friendly project, I am having fun :)

**Comment by Bertram25** [comment]
Np, it's always cool to get help. :)

**Pull request merged**
