### PR TITLE
pngcrush is a great friend to reduce size of PNG

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by Bertram25** [comment]
Hey,

We used optipng and such before and sometimes it gives bad alignment of pixels for the SDL loader, making the images look bad in game. Just in case, have you at least checked one of those files in the game afterward?

Cheers,

**Comment by RyDroid** [comment]
No. Do you have an easy way to reproduce a potential error (finding the image in the game can take time)? If yes, I could try to do a diff of what was rendered in a not compressed format.

**Comment by Bertram25** [comment]
Unfortunately, not really. the thing is we are using SDL image loader to load png pixels and remap the pixel buffers for OpenGL. This makes some rare edge case not handled very well, unfortunately. I remember the skeleton enemy being botched once the optipng was used. The only way is to make a game scene using the image and add it into the test scenes. (You'll have to compile using DEBUG_FEATURES=on) to get the menu available.

I'll try this one whenever I've got the time to.
Cheers,

**Comment by Bertram25** [comment]
Pushed as 068c2fd40d4732acc24c74e6ec96e46b6feb6fef

I rewrote the commit message to state what it does. (Looked like some ad for png crush before ;])

**Pull request closed without merging**
